# Generated by Django 5.0.6 on 2024-06-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_action_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='action_time',
            field=models.PositiveIntegerField(default=60, verbose_name='время на выполнение (сек)'),
        ),
    ]
